// Static mapping of country short codes to full country names
// This data is based on the Kurasi API and won't change frequently
export const countryMap: Record<string, string> = {
  // "AF": "Afghanistan",
  "AL": "Albania",
  "DZ": "Algeria",
  "AS": "American Samoa",
  "AD": "Andorra",
  "AO": "Angola",
  "AI": "Anguilla",
  "AG": "Antigua and Barbuda",
  "AR": "Argentina",
  "AM": "Armenia",
  "AW": "Aruba",
  "AU": "Australia",
  "AT": "Austria",
  "AZ": "Azerbaijan",
  "BS": "Bahamas",
  "BH": "Bahrain",
  "BD": "Bangladesh",
  "BB": "Barbados",
  "BY": "Belarus",
  "BE": "Belgium",
  "BZ": "Belize",
  "BJ": "Benin",
  "BM": "Bermuda",
  "BT": "Bhutan",
  "BO": "Bolivia",
  "XB": "Bonaire",
  "BA": "Bosnia and Herzegovina",
  "BW": "Botswana",
  "BR": "Brazil",
  "VG": "British Virgin Islands",
  "BN": "Brunei",
  "BG": "Bulgaria",
  "BF": "Burkina Faso",
  "BI": "Burundi",
  "KH": "Cambodia",
  "CM": "Cameroon",
  "CA": "Canada",
  "IC": "Canary Islands",
  "CV": "Cape Verde",
  "KY": "Cayman Islands",
  "CF": "Central African Republic",
  "TD": "Chad",
  "CL": "Chile",
  "CN": "China",
  "CO": "Colombia",
  "KM": "Comoros",
  "CG": "Congo",
  "CD": "Congo, DPR",
  "CK": "Cook Islands",
  "CR": "Costa Rica",
  "CI": "Cote D Ivoire",
  "HR": "Croatia",
  "CU": "Cuba",
  "CW": "Curacao",
  "CY": "Cyprus",
  "CZ": "Czech Republic",
  "DK": "Denmark",
  "DJ": "Djibouti",
  "DM": "Dominica",
  "DO": "Dominican Republic",
  "TL": "East Timor",
  "EC": "Ecuador",
  "EG": "Egypt",
  "SV": "El Salvador",
  "GQ": "Equatorial Guinea",
  "ER": "Eritrea",
  "EE": "Estonia",
  "ET": "Ethiopia",
  "FK": "Falkland Islands",
  "FO": "Faroe Islands",
  "FJ": "Fiji",
  "FI": "Finland",
  "FR": "France",
  "GF": "French Guiana",
  "GA": "Gabon",
  "GM": "Gambia",
  "GE": "Georgia",
  "DE": "Germany",
  "GH": "Ghana",
  "GI": "Gibraltar",
  "GR": "Greece",
  "GL": "Greenland",
  "GD": "Grenada",
  "GP": "Guadeloupe",
  "GU": "Guam",
  "GT": "Guatemala",
  "GG": "Guernsey",
  "GN": "Guinea",
  "GW": "Guinea-Bissau",
  "GY": "Guyana",
  "HT": "Haiti",
  "HN": "Honduras",
  "HK": "Hong Kong",
  "HU": "Hungary",
  "IS": "Iceland",
  "IN": "India",
  "ID": "Indonesia",
  "IR": "Iran",
  "IQ": "Iraq",
  "IE": "Ireland",
  "IL": "Israel",
  "IT": "Italy",
  "JM": "Jamaica",
  "JP": "Japan",
  "JE": "Jersey",
  "JO": "Jordan",
  "KZ": "Kazakhstan",
  "KE": "Kenya",
  "KI": "Kiribati",
  "XK": "Kosovo",
  "KW": "Kuwait",
  "KG": "Kyrgyzstan",
  "LA": "Laos",
  "LV": "Latvia",
  "LB": "Lebanon",
  "LS": "Lesotho",
  "LR": "Liberia",
  "LY": "Libya",
  "LI": "Liechtenstein",
  "LT": "Lithuania",
  "LU": "Luxembourg",
  "MO": "Macau",
  "MG": "Madagascar",
  "MW": "Malawi",
  "MY": "Malaysia",
  "MV": "Maldives",
  "ML": "Mali",
  "MT": "Malta",
  "MH": "Marshall Islands",
  "MQ": "Martinique",
  "MR": "Mauritania",
  "MU": "Mauritius",
  "YT": "Mayotte",
  "MX": "Mexico",
  "FM": "Micronesia",
  "MD": "Moldova",
  "MC": "Monaco",
  "MN": "Mongolia",
  "ME": "Montenegro",
  "MS": "Montserrat",
  "MA": "Morocco",
  "MZ": "Mozambique",
  "MM": "Myanmar",
  "NA": "Namibia",
  "NR": "Nauru",
  "NP": "Nepal",
  "NL": "Netherlands",
  "NC": "New Caledonia",
  "NZ": "New Zealand",
  "NI": "Nicaragua",
  "NE": "Niger",
  "NG": "Nigeria",
  "NU": "Niue",
  "MK": "North Macedonia",
  "MP": "Northern Mariana Islands",
  "NO": "Norway",
  "OM": "Oman",
  "PK": "Pakistan",
  "PW": "Palau",
  "PA": "Panama",
  "PG": "Papua New Guinea",
  "PY": "Paraguay",
  "PE": "Peru",
  "PH": "Philippines",
  "PL": "Poland",
  "PT": "Portugal",
  "PR": "Puerto Rico",
  "QA": "Qatar",
  "RE": "Reunion, Island Of",
  "RO": "Romania",
  "RU": "Russian Federation",
  "RW": "Rwanda",
  "BL": "Saint Barthelemy",
  "BQ": "Saint Eustatius",
  "SH": "Saint Helena",
  "KN": "Saint Kitts and Nevis",
  "LC": "Saint Lucia",
  "VC": "Saint Vincent",
  "WS": "Samoa",
  "SM": "San Marino",
  "ST": "Sao Tome And Principe",
  "SA": "Saudi Arabia",
  "SN": "Senegal",
  "RS": "Serbia",
  "SC": "Seychelles",
  "SL": "Sierra Leone",
  "SG": "Singapore",
  "SX": "Sint Maarten",
  "SK": "Slovakia",
  "SI": "Slovenia",
  "SB": "Solomon Islands",
  "SO": "Somalia",
  "XS": "Somaliland",
  "ZA": "South Africa",
  "KR": "South Korea",
  "SS": "South Sudan",
  "ES": "Spain",
  "LK": "Sri Lanka",
  "SD": "Sudan",
  "SR": "Suriname",
  "SZ": "Swaziland",
  "SE": "Sweden",
  "CH": "Switzerland",
  "SY": "Syria",
  "PF": "Tahiti, French Polynesia",
  "TW": "Taiwan",
  "TJ": "Tajikistan",
  "TZ": "Tanzania",
  "TH": "Thailand",
  "TG": "Togo",
  "TO": "Tonga",
  "TT": "Trinidad and Tobago",
  "TN": "Tunisia",
  "TR": "Turkey",
  "TC": "Turks and Caicos Islands",
  "TV": "Tuvalu",
  "VI": "U.S. Virgin Islands",
  "UG": "Uganda",
  "UA": "Ukraine",
  "AE": "United Arab Emirates",
  "GB": "United Kingdom",
  "US": "United States",
  "UY": "Uruguay",
  "UZ": "Uzbekistan",
  "VU": "Vanuatu",
  "VA": "Vatican City",
  "VE": "Venezuela",
  "VN": "Vietnam",
  "YE": "Yemen",
  "ZM": "Zambia",
  "ZW": "Zimbabwe"
};

export const countryCodes = new Set(Object.keys(countryMap));

export function normalizeCountryCode(input: unknown): string | null {
  if (typeof input !== "string") return null;
  const code = input.trim().toUpperCase();
  return countryCodes.has(code) ? code : null;
}

// Helper function to get full country name from short code
export function getFullCountryName(shortCode: string): string {
  return countryMap[shortCode] || shortCode;
}
// Static phone code map from Kurasi reference (digits only, no "+")
export const phoneCodeMap: Record<string, string> = {
  "AL": "355",
  "DZ": "213",
  "AS": "1",
  "AD": "376",
  "AO": "244",
  "AI": "1",
  "AG": "1",
  "AR": "54",
  "AM": "374",
  "AW": "297",
  "AU": "61",
  "AT": "43",
  "AZ": "994",
  "BS": "1",
  "BH": "973",
  "BD": "880",
  "BB": "1",
  "BY": "375",
  "BE": "32",
  "BZ": "501",
  "BJ": "229",
  "BM": "1",
  "BT": "975",
  "BO": "591",
  "XB": "599",
  "BA": "387",
  "BW": "267",
  "BR": "55",
  "VG": "1",
  "BN": "673",
  "BG": "359",
  "BF": "226",
  "BI": "257",
  "KH": "855",
  "CM": "237",
  "CA": "1",
  "IC": "34",
  "CV": "238",
  "KY": "1",
  "CF": "236",
  "TD": "235",
  "CL": "56",
  "CN": "86",
  "CO": "57",
  "KM": "269",
  "CG": "242",
  "CD": "243",
  "CK": "682",
  "CR": "506",
  "CI": "225",
  "HR": "385",
  "CW": "599",
  "CY": "357",
  "CZ": "420",
  "DK": "45",
  "DJ": "253",
  "DM": "1",
  "DO": "1",
  "TL": "670",
  "EC": "593",
  "EG": "20",
  "SV": "503",
  "GQ": "240",
  "ER": "291",
  "EE": "372",
  "ET": "251",
  "FK": "500",
  "FO": "298",
  "FJ": "679",
  "FI": "358",
  "FR": "33",
  "GF": "594",
  "GA": "241",
  "GM": "220",
  "GE": "995",
  "DE": "49",
  "GH": "233",
  "GI": "350",
  "GR": "30",
  "GL": "299",
  "GD": "1",
  "GP": "590",
  "GU": "1",
  "GT": "502",
  "GG": "44",
  "GN": "224",
  "GW": "245",
  "GY": "592",
  "HT": "509",
  "HN": "504",
  "HK": "852",
  "HU": "36",
  "IS": "354",
  "IN": "91",
  "IE": "353",
  "IL": "972",
  "IT": "39",
  "JM": "1",
  "JP": "81",
  "JE": "44",
  "JO": "962",
  "KZ": "7",
  "KE": "254",
  "KI": "686",
  "XK": "383",
  "KW": "965",
  "KG": "996",
  "LA": "856",
  "LV": "371",
  "LB": "961",
  "LS": "266",
  "LR": "231",
  "LY": "218",
  "LI": "423",
  "LT": "370",
  "LU": "352",
  "MO": "853",
  "MG": "261",
  "MW": "265",
  "MY": "60",
  "MV": "960",
  "ML": "223",
  "MT": "356",
  "MH": "692",
  "MQ": "596",
  "MR": "222",
  "MU": "230",
  "YT": "262",
  "MX": "52",
  "FM": "691",
  "MD": "373",
  "MC": "377",
  "MN": "976",
  "ME": "382",
  "MS": "1",
  "MA": "212",
  "MZ": "258",
  "MM": "95",
  "NA": "264",
  "NR": "674",
  "NP": "977",
  "NL": "31",
  "NC": "687",
  "NZ": "64",
  "NI": "505",
  "NE": "227",
  "NG": "234",
  "NU": "683",
  "MK": "389",
  "MP": "1",
  "NO": "47",
  "OM": "968",
  "PK": "92",
  "PW": "680",
  "PA": "507",
  "PG": "675",
  "PY": "595",
  "PE": "51",
  "PH": "63",
  "PL": "48",
  "PT": "351",
  "PR": "1",
  "QA": "974",
  "RE": "262",
  "RO": "40",
  "RW": "250",
  "BL": "590",
  "BQ": "599",
  "SH": "290",
  "KN": "1",
  "LC": "1",
  "VC": "1",
  "WS": "685",
  "SM": "378",
  "ST": "239",
  "SA": "966",
  "SN": "221",
  "RS": "381",
  "SC": "248",
  "SL": "232",
  "SG": "65",
  "SX": "1",
  "SK": "421",
  "SI": "386",
  "SB": "677",
  "SO": "252",
  "XS": "252",
  "ZA": "27",
  "KR": "82",
  "SS": "211",
  "ES": "34",
  "LK": "94",
  "SR": "597",
  "SZ": "268",
  "SE": "46",
  "CH": "41",
  "PF": "689",
  "TW": "886",
  "TJ": "992",
  "TZ": "255",
  "TH": "66",
  "TG": "228",
  "TO": "676",
  "TT": "1",
  "TN": "216",
  "TR": "90",
  "TC": "1",
  "TV": "688",
  "VI": "1",
  "UG": "256",
  "UA": "380",
  "AE": "971",
  "GB": "44",
  "US": "1",
  "UY": "598",
  "UZ": "998",
  "VU": "678",
  "VA": "379",
  "VE": "58",
  "VN": "84",
  "YE": "967",
  "ZM": "260",
  "ZW": "263"
};

// Helper to retrieve digits-only phone code
export function getPhoneCodeForCountry(shortCode: string): string {
  const raw = phoneCodeMap[String(shortCode || "").toUpperCase()];
  return raw ? String(raw).replace(/\D/g, "") : "";
}